CREATE TABLE IF NOT EXISTS reparaciones (
    id BIGSERIAL PRIMARY KEY,
    rut_cliente VARCHAR(20) NOT NULL,
    model VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'RECEIVED'
);
