server.port=8086
spring.application.name=ms-garantia

jwt.secret=smartfix-secret-key-256-bits-minimo-para-hs256-aqui
jwt.expiration-ms=3600000

sentry.dsn=${SENTRY_DSN:}
sentry.environment=${SENTRY_ENVIRONMENT:development}
sentry.logging.minimum-event-level=error
sentry.logging.minimum-breadcrumb-level=info
sentry.traces-sample-rate=1.0
