server.port=8092

spring.datasource.url=jdbc:postgresql://localhost:5437/db_smartfix_auditoria
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=smartfix-secret-key-256-bits-minimo-para-hs256-aqui
jwt.expiration-ms=3600000

sentry.dsn=${SENTRY_DSN:}
sentry.environment=${SENTRY_ENVIRONMENT:development}
sentry.logging.minimum-event-level=error
sentry.logging.minimum-breadcrumb-level=info
sentry.traces-sample-rate=1.0
